#ifndef PCH_H
#define PCH_H

#include <glad/glad.h>
#include <glad/KHR/khrplatform.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/glm.hpp>
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>
#include <glm/mat3x3.hpp>
#include <glm/mat4x4.hpp>
#include <glm/gtc/type_ptr.hpp>
#include "Core.h"
#include "Window.h"
#include "Logging/Loging.h"
#include "Logging/Asserts.h"
#include "Events/KeyCodes.h"
#include "Events/Events.h"
#include "Graphics/GraphicsUtils.h"
#include "Graphics/Shader.h"
#include "Graphics/Mesh.h"
#include <iostream>
#include <stdio.h>
#include <cstdarg>
#include <stdarg.h>
#include <string>
#include <vector>

#endif //PCH_H